#!/usr/bin/env python3
"""Build the tiny Noto Sans SC subset used by the Chinese promo.

Noto Sans SC is ~10 MB per weight, so the storyboard ships only the glyphs its
Chinese copy actually uses. Re-run this after editing the `zh` strings in
promo.html (the generator warns when a character is missing).

Usage:
  npm pack @fontsource/noto-sans-sc@5 && tar xzf fontsource-noto-sans-sc-*.tgz
  python3 scripts/promo/build-zh-font.py package/ chars.txt scripts/promo/fonts/

`chars.txt` holds every character the zh storyboard renders; the generator can
dump it (node scripts/generate-promo-video.mjs --dump-zh-chars chars.txt).
Needs: pip install fonttools brotli
"""
import re
import sys
from pathlib import Path

from fontTools import subset
from fontTools.merge import Merger
from fontTools.ttLib import TTFont

WEIGHTS = (500, 700, 800)

pkg, chars_file, out_dir = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
# Latin, digits and ASCII punctuation come from Inter; only keep what Inter cannot draw.
needed = {c for c in chars_file.read_text(encoding='utf-8') if ord(c) > 0x2E7F}
if not needed:
    sys.exit('no CJK characters found')


def ranges(spec):
    for part in spec.split(','):
        lo, _, hi = part.strip()[2:].partition('-')
        yield int(lo, 16), int(hi or lo, 16)


css_out = [f'/* Generated by scripts/promo/build-zh-font.py: Noto Sans SC (SIL OFL 1.1), '
           f'{len(needed)} glyphs used by the zh storyboard. */']
for weight in WEIGHTS:
    css = (pkg / f'{weight}.css').read_text()
    chunks = []
    for block in re.findall(r'@font-face\s*{(.*?)}', css, re.S):
        url = re.search(r'url\(\./files/([^)]+\.woff2)\)', block).group(1)
        spans = list(ranges(re.search(r'unicode-range:\s*([^;]+);', block).group(1)))
        hit = {c for c in needed if any(lo <= ord(c) <= hi for lo, hi in spans)}
        if hit:
            chunks.append((pkg / 'files' / url, hit))

    parts, covered = [], set()
    for i, (path, hit) in enumerate(chunks):
        font = TTFont(path)
        opts = subset.Options()
        opts.layout_features = ['*']
        opts.name_IDs = ['*']
        opts.notdef_outline = True
        sub = subset.Subsetter(opts)
        sub.populate(text=''.join(sorted(hit)))
        sub.subset(font)
        tmp = out_dir / f'.part-{weight}-{i}.ttf'
        font.flavor = None
        font.save(tmp)
        parts.append(tmp)
        covered |= hit

    merged = Merger().merge([str(p) for p in parts]) if len(parts) > 1 else TTFont(parts[0])
    merged.flavor = 'woff2'
    target = out_dir / f'noto-sans-sc-subset-{weight}.woff2'
    merged.save(target)
    for p in parts:
        p.unlink()
    missing = needed - covered
    print(f'{target.name}: {len(covered)} glyphs from {len(chunks)} chunks, {target.stat().st_size // 1024} KB'
          + (f', MISSING {"".join(sorted(missing))}' if missing else ''))
    css_out.append(f'@font-face {{ font-family: "Noto Sans SC"; font-weight: {weight}; font-display: block; '
                   f'src: url("noto-sans-sc-subset-{weight}.woff2") format("woff2"); }}')

(out_dir / 'noto-sans-sc-subset.css').write_text('\n'.join(css_out) + '\n', encoding='utf-8')
