#!/usr/bin/env node
/**
 * scripts/test-rules.mjs
 *
 * validate.mjs 的规则有效性自测（变异测试 / Mutation Test）
 * ────────────────────────────────────────────────────────────────
 * 一个"什么都能过"的校验器等于没有校验器。本脚本为每条规则
 * 生成一份**恰好含一处缺陷**的合成 HTML，断言对应规则确实命中；
 * 同时用反向用例断言白名单与豁免机制不会误报。
 *
 * 用法：node scripts/test-rules.mjs
 * 退出码：0 = 全部通过；1 = 有用例未达预期
 */

import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
// 正本在技能目录内（随技能分发），本脚本是仓库侧的维护工具
const VALIDATOR = join(ROOT, 'skills', 'agent-html', 'scripts', 'validate.mjs');

/* ── 一份通过全部规则的基准文件 ────────────────────────────────── */
const BASE = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Fixture</title>
<style>
  :root { --bg: #fafafa; --card: #ffffff; --card-fg: #09090b; --primary: #18181b; --primary-fg: #fafafa; --border: #e4e4e7; --muted-fg: #71717a; }
  [data-theme="dark"] { --bg: #09090b; --card: #121215; --card-fg: #fafafa; --primary: #fafafa; --primary-fg: #18181b; --border: #27272a; --muted-fg: #a1a1aa; }
  body { background: var(--bg); color: var(--card-fg); }
  .container { max-width: 1280px; width: 100%; margin: 0 auto; }
  @media print { body { background: #fff; padding: 0; } }
</style>
</head>
<body>
<div class="container">
  <button id="copyBtn" onclick="copyMd()">Copy</button>
  <div id="out">ready</div>
  <footer>Generated by agent-html · zero-dependency · archived</footer>
</div>
<script>
  function copyMd() { navigator.clipboard.writeText('md'); }
</script>
</body>
</html>
`;

const withStyle = (css) => BASE.replace('</style>', `${css}\n</style>`);
const noPrint = () => BASE.replace(/\s*@media print \{[^}]*\}/, '');

/* ── 用例表 ────────────────────────────────────────────────────
   expect 中的规则必须全部命中；同时断言没有出现 expect 之外的
   error 级规则（防止用例本身顺带触发别的缺陷，污染结论）。 */
const CASES = [
  {
    label: 'ZERO_CDN 必须拦截外部脚本',
    files: { 'cdn.html': BASE.replace('</head>', '<script src="https://cdn.example.com/x.js"></script>\n</head>') },
    expect: ['ZERO_CDN'],
  },
  {
    label: 'ZERO_CDN 必须拦截远程字体',
    files: { 'font.html': BASE.replace('</head>', '<link href="https://fonts.googleapis.com/css2?family=X" rel="stylesheet">\n</head>') },
    expect: ['ZERO_CDN'],
  },
  {
    label: 'THEME_TOKENS 必须发现缺失的 token 底座',
    // 只剥离 `--primary:` 的声明，保留 `--primary-fg:`——
    // 专门回归「子串检查会让 --primary-fg 蒙混过关」这个漏洞。
    files: { 'tokens.html': BASE.replace(/--primary:[^;]*;/g, '') },
    expect: ['THEME_TOKENS'],
  },
  {
    label: 'VIEWPORT 必须发现缺失的 viewport',
    files: { 'viewport.html': BASE.replace(/<meta name="viewport"[^>]*>\n/, '') },
    expect: ['VIEWPORT'],
  },
  {
    label: 'TAG_HYGIENE 必须发现未闭合的 details',
    files: { 'tags.html': BASE.replace('<div id="out">ready</div>', '<details><summary>a</summary><div id="out">ready</div>') },
    expect: ['TAG_HYGIENE'],
  },
  {
    label: 'DUP_ID 必须发现重复 id',
    files: { 'dupid.html': BASE.replace('<div id="out">ready</div>', '<div id="out">a</div><div id="out">b</div>') },
    expect: ['DUP_ID'],
  },
  {
    label: 'SCRIPT_SYNTAX 必须发现内联脚本语法错误',
    files: { 'syntax.html': BASE.replace('function copyMd() {', 'function copyMd( {') },
    expect: ['SCRIPT_SYNTAX'],
  },
  {
    label: 'DARK_MODE_LEAK 必须发现 token 块外的硬编码白色',
    files: { 'leak.html': withStyle('  .btn-x:hover { background: #3f3f46; color: #fff; }') },
    expect: ['DARK_MODE_LEAK'],
  },
  {
    label: 'WIDTH_HYGIENE 必须发现表格缺少横向滚动容器',
    files: { 'width.html': BASE.replace('<div id="out">ready</div>', '<table><tbody><tr><td>x</td></tr></tbody></table>') },
    expect: ['WIDTH_HYGIENE'],
  },
  {
    label: 'NO_RANDOM 必须发现 Math.random',
    files: { 'random.html': BASE.replace("writeText('md')", 'writeText(String(Math.random()))') },
    expect: ['NO_RANDOM'],
  },
  {
    label: 'CHART_TOKEN_ONLY 必须发现 SVG 硬编码色值',
    files: { 'chartcolor.html': BASE.replace('<div id="out">ready</div>', '<svg viewBox="0 0 10 10"><rect width="5" height="5" fill="#ff0000"/></svg>') },
    expect: ['CHART_TOKEN_ONLY'],
  },
  {
    label: 'FIXED_HEIGHT 必须发现固定高度 + overflow:hidden',
    files: { 'fixed.html': withStyle('  .box { height: 500px; overflow: hidden; }') },
    expect: ['FIXED_HEIGHT'],
  },
  {
    label: 'PRINT_STYLE 必须在文档型母版上判为阻断',
    files: { 'report.html': noPrint() },
    expect: ['PRINT_STYLE'],
  },
  {
    label: 'EMPTY_STATE 必须发现"有筛选但无空状态"',
    files: {
      'empty.html': BASE.replace(
        'function copyMd() {',
        "document.getElementById('q')?.addEventListener('input', () => {});\n  function copyMd() {",
      ),
    },
    expect: ['EMPTY_STATE'],
  },

  /* ── 反向用例：这些**必须不报**，证明白名单与豁免生效 ── */
  {
    label: '白名单：token 定义块与 @media print 内的颜色字面量不得报错',
    files: { 'allowlist.html': withStyle('  .x { color: var(--card-fg); }') },
    expect: [],
    forbid: ['DARK_MODE_LEAK'],
  },
  {
    label: '行级豁免：@lint-allow 必须精确抑制指定行的命中',
    files: {
      'allowed.html': withStyle(
        '  /* @lint-allow: DARK_MODE_LEAK — 该按钮位于恒为深色的代码块表面上，不随主题反转 */\n' +
        '  .btn-y:hover { background: #3f3f46; color: #fff; }',
      ),
    },
    expect: [],
    forbid: ['DARK_MODE_LEAK'],
  },
  {
    label: '豁免必须有作用域：同文件其他位置的泄漏仍须被捕获',
    files: {
      'scoped.html': withStyle(
        '  /* @lint-allow: DARK_MODE_LEAK — 该按钮位于恒为深色的代码块表面上，不随主题反转 */\n' +
        '  .btn-y:hover { background: #3f3f46; color: #fff; }\n' +
        '  .btn-z { background: #fff; }',
      ),
    },
    expect: ['DARK_MODE_LEAK'],
  },
  {
    label: '豁免必须写理由：没写理由的 @lint-allow 不生效',
    files: {
      'noreason.html': withStyle('  /* @lint-allow: DARK_MODE_LEAK — 短 */\n  .btn-y { background: #fff; }'),
    },
    expect: ['DARK_MODE_LEAK'],
  },
  {
    label: 'MIN_FONT 必须发现 SVG 内低于 9px 的字号',
    files: { 'minfont.html': BASE.replace('</body>', '<svg viewBox="0 0 100 40" style="width:100px;height:40px"><text x="0" y="20" font-size="6">tiny</text><text x="0" y="35" font-size="10">ok</text></svg></body>') },
    expect: ['MIN_FONT'],
  },
  {
    label: 'CSS_VAR_DEFINED 必须发现未定义且无 fallback 的 CSS 变量',
    files: { 'undefvar.html': BASE.replace('background: var(--bg);', 'background: var(--bg); stroke: var(--nope);') },
    expect: ['CSS_VAR_DEFINED'],
  },
  {
    label: 'CSS_VAR_DEFINED 不得误报：带 fallback 的 var() 是合法的',
    files: { 'fallback.html': BASE.replace('background: var(--bg);', 'background: var(--bg); stroke: var(--nope, #333);') },
    expect: [],
    forbid: ['CSS_VAR_DEFINED'],
  },
  {
    label: '基准文件必须完全干净（0 阻断 / 0 提醒）',
    files: { 'clean.html': BASE },
    expect: [],
    forbidAll: true,
  },

  /* ── 规范文档完整性 ── */
  {
    label: 'DOC_FENCES 必须发现未闭合的代码块',
    files: { 'broken.md': '# Title\n\n```bash\nnpm test\n' },
    expect: ['DOC_FENCES'],
  },
  {
    label: 'DOC_SECTIONS 必须发现重复的章节编号',
    files: { 'dup.md': '# Title\n\n## 一、A\n\n## 一、B\n' },
    expect: ['DOC_SECTIONS'],
  },
  {
    label: 'DOC_SECTIONS 必须发现章节跳号',
    files: { 'gap.md': '# Title\n\n## 一、A\n\n## 三、C\n' },
    expect: ['DOC_SECTIONS'],
  },
  {
    label: 'DOC_SECTIONS 必须发现阿拉伯数字章节重复（组件字典用的是 1. 2. 3. 写法）',
    files: { 'dupnum.md': '# Title\n\n## 6. A\n\n## 6. B\n' },
    expect: ['DOC_SECTIONS'],
  },
  {
    label: '文档规则不得误伤合法 Markdown（围栏配对、编号连续）',
    files: { 'clean.md': '# Title\n\n```bash\nnpm test\n```\n\n## 一、A\n\n## 二、B\n' },
    expect: [],
    forbidAll: true,
  },
];

/* ── 中英同构用例（需要目录结构）──────────────────────────────── */
const PARITY_CASES = [
  {
    label: 'ZH_EN_PARITY 必须发现英文版缺失的结构元素',
    files: {
      'zh/page.html': BASE.replace('<div id="out">ready</div>', '<nav><a href="#">x</a></nav><div id="out">ready</div>'),
      'en/page.html': BASE,
    },
    expectParity: ['ZH_EN_PARITY'],
  },
  {
    label: 'ZH_EN_PARITY 结构一致时必须通过',
    files: {
      'zh/same.html': BASE.replace('<div id="out">ready</div>', '<nav><a href="#">x</a></nav><div id="out">ready</div>'),
      'en/same.html': BASE.replace('<div id="out">ready</div>', '<nav><a href="#">y</a></nav><div id="out">ready</div>'),
    },
    expectParity: [],
  },
];

/* ── 执行 ─────────────────────────────────────────────────────── */

const workDir = mkdtempSync(join(tmpdir(), 'agent-html-rules-'));
let passed = 0;
const failures = [];

function runCase(testCase) {
  const caseDir = mkdtempSync(join(workDir, 'case-'));
  const paths = [];
  for (const [rel, content] of Object.entries(testCase.files)) {
    const full = join(caseDir, rel);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, content, 'utf8');
    if (rel.endsWith('.html') || rel.endsWith('.md')) paths.push(full);
  }

  const run = spawnSync('node', [VALIDATOR, ...paths, '--json'], { encoding: 'utf8' });
  let parsed;
  try {
    parsed = JSON.parse(run.stdout);
  } catch {
    failures.push(`${testCase.label} → 校验器未返回合法 JSON\n${run.stdout}\n${run.stderr}`);
    return;
  }

  const fired = new Set();
  for (const result of parsed.results) for (const f of result.findings) fired.add(f.rule);
  for (const f of parsed.crossFile ?? []) fired.add(f.rule);

  const errs = [];
  for (const rule of testCase.expect ?? []) {
    if (!fired.has(rule)) errs.push(`期望命中 ${rule}，实际未命中`);
  }
  for (const rule of testCase.forbid ?? []) {
    if (fired.has(rule)) errs.push(`期望不命中 ${rule}，实际命中了`);
  }
  for (const rule of testCase.expectParity ?? []) {
    if (!fired.has(rule)) errs.push(`期望命中 ${rule}，实际未命中`);
  }
  if (testCase.forbidAll && (parsed.errors > 0 || parsed.warnings > 0)) {
    errs.push(`基准文件应为 0 阻断 / 0 提醒，实际 ${parsed.errors} / ${parsed.warnings}：${[...fired].join(', ')}`);
  }

  if (errs.length) failures.push(`${testCase.label}\n    - ${errs.join('\n    - ')}`);
  else passed += 1;
}

process.stdout.write(`\n🧪 validate.mjs 规则有效性自测 · ${CASES.length + PARITY_CASES.length} 个用例\n\n`);
for (const testCase of [...CASES, ...PARITY_CASES]) runCase(testCase);

rmSync(workDir, { recursive: true, force: true });

if (failures.length) {
  process.stderr.write(`❌ ${failures.length} 个用例未达预期：\n\n`);
  for (const f of failures) process.stderr.write(`  ${f}\n\n`);
  process.exit(1);
}
process.stdout.write(`✅ 全部通过：${passed} 个用例（每条规则都被证明能捕获对应的真实缺陷，且白名单与豁免不误报）\n\n`);
