#!/usr/bin/env node
/**
 * scripts/validate.mjs
 * 
 * 极轻量单文件 HTML 确定性静态校验器（Zero-Dependency Structural Linter）
 * 供 AI Agent 生成完单文件 HTML 产物后，在本地终端执行快速自验。
 * 
 * 校验规则：
 * 1. [ZERO_CDN]      严禁引入任何外网 script/link/font CDN 资源（杜绝断网白屏与 CSP 拦截）
 * 2. [THEME_TOKENS]  必须声明完整 shadcn 风格的 CSS 变量底座并支持暗黑模式
 * 3. [VIEWPORT]      必须包含移动端/小屏响应式 viewport meta
 * 4. [TAG_HYGIENE]   基础标签对称性自检（svg/details/dialog/style/script 是否闭合）
 * 5. [AFFORDANCE]    必须具备“复制/导出”出口（杜绝无数据流回终端的“交互死胡同”）
 * 6. [COLOPHON]      建议包含页脚溯源元数据印章
 * 
 * 用法：
 *   node scripts/validate.mjs <file.html>
 *   node scripts/validate.mjs --all
 */

import { readFileSync, existsSync, readdirSync, realpathSync } from 'node:fs';
import { resolve, join, relative } from 'node:path';
import { exit, argv, stdout, stderr } from 'node:process';

const args = argv.slice(2);
if (args.length === 0 || args.includes('-h') || args.includes('--help')) {
  stdout.write(`用法:
  node scripts/validate.mjs <file.html>     # 校验单个 HTML 文件
  node scripts/validate.mjs --all           # 校验仓库内置所有画廊与母版 HTML
`);
  exit(0);
}

function findHtmlFiles(dir) {
  let files = [];
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.name === 'node_modules' || entry.name === '.git') continue;
    if (entry.isDirectory()) {
      files = files.concat(findHtmlFiles(full));
    } else if (entry.isFile() && entry.name.endsWith('.html')) {
      try {
        files.push(realpathSync(full));
      } catch {
        files.push(resolve(full));
      }
    }
  }
  return files;
}

const targetFiles = [];
if (args.includes('--all')) {
  targetFiles.push(resolve('index.html'));
  if (existsSync(resolve('index.zh-CN.html'))) {
    targetFiles.push(resolve('index.zh-CN.html'));
  }
  const tplDir = resolve('templates');
  if (existsSync(tplDir)) {
    targetFiles.push(...findHtmlFiles(tplDir));
  }
} else {
  for (const a of args) {
    if (!a.startsWith('-')) {
      const p = resolve(a);
      if (!existsSync(p)) {
        stderr.write(`❌ 找不到文件: ${a}\n`);
        exit(1);
      }
      try {
        targetFiles.push(realpathSync(p));
      } catch {
        targetFiles.push(p);
      }
    }
  }
}

// 基于真实物理路径精准去重并按路径排序
const uniqueFiles = Array.from(new Set(targetFiles)).sort();
if (uniqueFiles.length === 0) {
  stderr.write('未指定待校验的 HTML 文件。\n');
  exit(1);
}

let totalErrors = 0;
let totalWarnings = 0;

stdout.write(`\n🔍 开始执行 Agent HTML 单文件静态自验规范检查 (${uniqueFiles.length} 个文件)...\n\n`);

for (const file of uniqueFiles) {
  const rel = relative(process.cwd(), file) || file;
  const content = readFileSync(file, 'utf8');
  const errors = [];
  const warnings = [];

  // 1. [ZERO_CDN] 绝对杜绝外部 CDN
  const cdnScriptMatch = content.match(/<script\b[^>]*\bsrc=["'](https?:)?\/\/[^"'>]+/gi);
  if (cdnScriptMatch) {
    errors.push(`发现外部 CDN Script 引用 (${cdnScriptMatch.length} 处)，严禁违背 Zero-CDN 规范: ${cdnScriptMatch[0]}`);
  }
  const cdnLinkMatch = content.match(/<link\b[^>]*\bhref=["'](https?:)?\/\/[^"'>]+/gi);
  if (cdnLinkMatch) {
    errors.push(`发现外部 CDN 样式或字体 Link (${cdnLinkMatch.length} 处): ${cdnLinkMatch[0]}`);
  }
  const cssImportMatch = content.match(/@import\s+(url\()?["'](https?:)?\/\/[^"')]+/gi);
  if (cssImportMatch) {
    errors.push(`发现 CSS 外部 @import: ${cssImportMatch[0]}`);
  }

  // 2. [THEME_TOKENS] 暗黑模式与变量底座
  const hasRoot = content.includes(':root');
  const hasDark = content.includes('data-theme="dark"') || content.includes('prefers-color-scheme');
  const hasTokens = content.includes('--bg') && content.includes('--card') && content.includes('--primary') && content.includes('--border');
  if (!hasRoot || !hasTokens) {
    errors.push('缺少核心 Micro-CSS 变量底座（需声明 --bg, --card, --primary, --border）');
  }
  if (!hasDark) {
    warnings.push('未检测到暗黑模式支持 (需支持 data-theme="dark" 或 prefers-color-scheme)');
  }

  // 3. [VIEWPORT]
  if (!content.includes('name="viewport"') && !content.includes("name='viewport'")) {
    errors.push('缺少 <meta name="viewport"> 声明，可能导致移动端及小视口渲染异常');
  }

  // 4. [TAG_HYGIENE] 常见双标签对称闭合度快速检查
  const tagsToCheck = ['svg', 'dialog', 'details', 'style', 'script'];
  for (const tag of tagsToCheck) {
    const openCount = (content.match(new RegExp(`<${tag}\\b`, 'gi')) || []).length;
    const closeCount = (content.match(new RegExp(`<\/${tag}>`, 'gi')) || []).length;
    if (openCount !== closeCount) {
      errors.push(`标签 <${tag}> 开闭不匹配: 开标签 ${openCount} 个, 闭标签 ${closeCount} 个`);
    }
  }

  // 5. [AFFORDANCE] 复制/导出闭环出口 (避免死胡同)
  const hasExport = /clipboard|copy|export|print|复制|导出/i.test(content);
  if (!hasExport) {
    warnings.push('未检测到数据复制或导出按钮 (交互死胡同)。建议提供“复制结果 / 导出 Markdown”让用户能将决策带回 Agent');
  }

  // 6. [COLOPHON] 溯源印章
  const hasColophon = /colophon|generated by|时间戳|归档/i.test(content);
  if (!hasColophon) {
    warnings.push('未检测到页脚 Colophon 溯源印章，建议在页脚补充生成时间与上下文标识');
  }

  // 输出单文件报告
  if (errors.length === 0 && warnings.length === 0) {
    stdout.write(`  ✅ \x1b[32mPASS\x1b[0m  ${rel}\n`);
  } else if (errors.length === 0) {
    stdout.write(`  ⚠️  \x1b[33mWARN\x1b[0m  ${rel} (${warnings.length} 项提醒)\n`);
    warnings.forEach(w => stdout.write(`      \x1b[33m- [提醒]\x1b[0m ${w}\n`));
  } else {
    stdout.write(`  ❌ \x1b[31mFAIL\x1b[0m  ${rel} (${errors.length} 处违背规范)\n`);
    errors.forEach(e => stdout.write(`      \x1b[31m- [阻断]\x1b[0m ${e}\n`));
    warnings.forEach(w => stdout.write(`      \x1b[33m- [提醒]\x1b[0m ${w}\n`));
  }

  totalErrors += errors.length;
  totalWarnings += warnings.length;
}

stdout.write('\n' + '─'.repeat(60) + '\n');
if (totalErrors === 0) {
  stdout.write(`🎉 校验全部通过！0 项阻断错误，${totalWarnings} 项规范提醒。\n\n`);
  exit(0);
} else {
  stdout.write(`🚨 校验未通过！发现 ${totalErrors} 处规范阻断错误，${totalWarnings} 项规范提醒。\n\n`);
  exit(1);
}
